### ISSUE TITLE
Standalone build instructions

### ISSUE THREAD

**Issue by Gudahtt** [GraphFoundation/neo4j-oe#1]
The standalone build instructions appear to be missing. These were [removed in this commit from the Neo4j git repository](https://github.com/neo4j/neo4j/commit/affe1a0b4ab47c9d4673bfa507868ccd03c48ddd), as explained in [this blog post](https://blog.igovsol.com/2017/11/14/Neo4j-330-is-out-but-where-are-the-open-source-enterprise-binaries.html).

If I am not mistaken, these build instructions would need to have been restored in order to produce the ONgDB tarball and zip files made available by the Graph Foundation.

Where are these build instructions? Can they be restored to this repo or the Graph Foundation Neo4j fork, so that others can produce the same distributions independently?

**Comment by jmsuhy** [comment]
There will be a new maven project called ongdb-packaging which will allow you to build the distribution yourself.   It will be a separate git repo under the graph foundation, and will have instructions, etc.

**Comment by Gudahtt** [comment]
Ok, sounds great. Thanks.

**Comment by jmsuhy** [comment]
Check the foundation github site for the update.  I'll let you know as well via a message when up as well.

**Comment by Gudahtt** [comment]
I haven't heard back about this, but it looks like the standalone build instructions are here: https://github.com/graphfoundation/ongdb/tree/3.5/packaging/standalone/standalone-enterprise

Just in case anyone else is looking for them
